### ISSUE TITLE
TypeError: kernel_initializer keyword not understood when building a dense layer. 

### ISSUE THREAD

**Issue by decisivesacha** [dmlc/keras#100]
Here is the output:
Using MXNet backend.
Traceback (most recent call last):
  File "run.py", line 128, in <module>
    model = Model(config_args['alpha'], config_args['gamma'], config_args['input_size'], config_args['hidden_size'])
  File "/tmp/Model.py", line 37, in __init__
    kernel_initializer='glorot_normal'))
  File "/usr/local/lib/python3.6/dist-packages/Keras-1.2.2-py3.6.egg/keras/layers/core.py", line 785, in __init__
    super(Dense, self).__init__(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Keras-1.2.2-py3.6.egg/keras/engine/topology.py", line 326, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'kernel_initializer')

The same issue comes up for use_bias = False. 

Not sure why this is the case.
I'm using the master version from this repo. Version 1.2.2 with python 3.67 and mxnet 1.3.1

**Comment by decisivesacha** [comment]
keras.clone_model does not seem to have been ported over either as this is throwing an import error.
